/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelroombookingsystem;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.Box;
import javax.swing.JOptionPane;

public class createbooking extends javax.swing.JFrame {
    //class
class Customer
{
    //set modifier and create variables
protected String name, icpp, email;
protected int phnum;
//constructor
Customer(String n, String i, int p, String e)
{
    //set value
    name = n;
    icpp = i;
    email = e;
    phnum = p;
}
}
//subclass-inheritance
class Booking extends Customer
{
    // set modifire and create variables
    protected String daytostay, roomid, date, dateafter;
    //constructor
    Booking(String n, String i, int p, String e,String r, String d,String dts, String da) //parameters
    {
        super(n,i,p,e);// calling super class constructor
        //set value
        date = d;
        dateafter = da;
        daytostay = dts;
        roomid = r;
    }
    //encapsulation
    // to get name
    public String getName()
    {
        return name;
    }
    //to get ic/passport
    public String geticpp()
    {
        return icpp;
    }
    //to get phone number
    public int getphnum()
    {
        return phnum;
    }
    //to get email
    public String getemail()
    {
        return email;
    }
    //to get room id
    public String getroomid()
    {
        return roomid;
    }
    //to get date after staying
    public String getdateafter()
    {
        return dateafter;
    }
    //to get date start booking
    public String getdate()
    {
        return date;
    }
    //to get total day to stay
    public String getdaytostay()
    {
        return daytostay;
    }   
}
//to get date
Calendar c = new GregorianCalendar();
//to get date
Calendar cextra = new GregorianCalendar();
//set date format
SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    public createbooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtICPP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbID = new javax.swing.JComboBox<>();
        txtPhone = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbDos = new javax.swing.JComboBox<>();
        txtCheckout = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuitemhomepage = new javax.swing.JMenuItem();
        menuitemcreatebooking = new javax.swing.JMenuItem();
        menuitemviewbooking = new javax.swing.JMenuItem();
        menuitemeditbooking = new javax.swing.JMenuItem();
        menuitemdeletebooking = new javax.swing.JMenuItem();
        menuitemreceipt = new javax.swing.JMenuItem();
        exitmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setText("Create Booking");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel4.setText("Contact No:");

        cbID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "Room1", "Room2", "Room3", "Room4", "Room5", "Room6", "Room7", "Room8", "Room9", "Room10", "Room11", "Room12", "Room13", "Room14", "Room15", "Room16", "Room17", "Room18", "Room19", "Room20" }));
        cbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIDActionPerformed(evt);
            }
        });

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 0, 51));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel5.setText("Email:");

        jDateChooser1.setToolTipText("");
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setDate(cextra.getTime());
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel6.setText("Room ID:");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel7.setText("Days of stay:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel8.setText("Check In Date:");

        cbDos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select", "1 day", "2 days", "3 days", "4 days", "5 days", "6 days", "7 days" }));
        cbDos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDosItemStateChanged(evt);
            }
        });

        txtCheckout.setEditable(false);
        txtCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel2.setText("Customer Name:");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel9.setText("CheckOut Date:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel3.setText("IC/ Passport:");

        btnSave.setBackground(new java.awt.Color(0, 204, 51));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtICPP, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDos, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnReset))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnReset, btnSave});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbDos, cbID, jDateChooser1, txtCheckout, txtEmail, txtICPP, txtName, txtPhone});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtICPP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSave))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnReset, btnSave});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cbDos, cbID, jDateChooser1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, txtCheckout, txtICPP, txtName, txtPhone});

        menu.setText("MENU");

        menuitemhomepage.setText("Homepage");
        menuitemhomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemhomepageActionPerformed(evt);
            }
        });
        menu.add(menuitemhomepage);

        menuitemcreatebooking.setText("Create Booking");
        menuitemcreatebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemcreatebookingActionPerformed(evt);
            }
        });
        menu.add(menuitemcreatebooking);

        menuitemviewbooking.setText("View Booking");
        menuitemviewbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemviewbookingActionPerformed(evt);
            }
        });
        menu.add(menuitemviewbooking);

        menuitemeditbooking.setText("Edit Booking");
        menuitemeditbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemeditbookingActionPerformed(evt);
            }
        });
        menu.add(menuitemeditbooking);

        menuitemdeletebooking.setText("Delete Booking");
        menuitemdeletebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemdeletebookingActionPerformed(evt);
            }
        });
        menu.add(menuitemdeletebooking);

        menuitemreceipt.setText("Receipt");
        menuitemreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemreceiptActionPerformed(evt);
            }
        });
        menu.add(menuitemreceipt);

        menubar.add(menu);

        exitmenu.setText("EXIT");
        exitmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitmenuMouseClicked(evt);
            }
        });

        menubar.add(Box.createHorizontalGlue());

        menubar.add(exitmenu);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemhomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemhomepageActionPerformed
        //to go to home page
        homepage homepage = new homepage();//set homepage as homepage
        homepage.setVisible(true);//open homepage page
        this.setVisible(false);//close current page

    }//GEN-LAST:event_menuitemhomepageActionPerformed

    private void menuitemcreatebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemcreatebookingActionPerformed
        //to go to create booking page
        createbooking c = new createbooking();// set create booking as c
        c.setVisible(true);// open create booking page
        this.setVisible(false);// close current page
    }//GEN-LAST:event_menuitemcreatebookingActionPerformed

    private void menuitemviewbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemviewbookingActionPerformed
        //to go to view booking page
        viewbooking page = new viewbooking();// set view booking as page
        page.setVisible(true);//open view booking page
        this.setVisible(false);//close current page
    }//GEN-LAST:event_menuitemviewbookingActionPerformed

    private void menuitemeditbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemeditbookingActionPerformed
        //to go to edit booking page
        editbooking c = new editbooking();// set editbooking as c
        c.setVisible(true);// open edit booking page
        this.setVisible(false);// close this page
    }//GEN-LAST:event_menuitemeditbookingActionPerformed

    private void menuitemdeletebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemdeletebookingActionPerformed
        //to go to delete booking page
        deletebooking c = new deletebooking();//set delete booking as c
        c.setVisible(true);//open delete booking page
        this.setVisible(false);//close this page
    }//GEN-LAST:event_menuitemdeletebookingActionPerformed

    private void menuitemreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemreceiptActionPerformed
        //to go to receipt page
        receipt c = new receipt();// set receipt as c
        c.setVisible(true);//open receipt page
        this.setVisible(false);//close this page
    }//GEN-LAST:event_menuitemreceiptActionPerformed

    private void exitmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitmenuMouseClicked
        int n = JOptionPane.showConfirmDialog(null,"Would you like to terminate?","Terminate System",JOptionPane.YES_NO_OPTION);//pop up box asking confirmation to exit the application
        if(n==JOptionPane.YES_OPTION)//if yes is clicked
        System.exit(0);//application exit

    }//GEN-LAST:event_exitmenuMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // to safe information into the file
        File file = new File("Booking.txt");// to search for Booking.txt text file
        int wrong=0;//declare vairable and assign value
        try
        {
            Scanner inputFile = new Scanner(file);
            while (inputFile.hasNext())
            {
                //getting information from the text file
                String n = inputFile.nextLine();
                String i = inputFile.nextLine();
                int p = inputFile.nextInt();
                inputFile.nextLine();
                String e = inputFile.nextLine();
                String r = inputFile.nextLine();
                String d = inputFile.nextLine();
                String dts = inputFile.nextLine();
                String da = inputFile.nextLine();
                inputFile.nextLine();
                // set the information into booking class
                Booking room = new Booking(n,i,p,e,r,d,dts,da);
                //to check if this ic or passport existed
                if (room.geticpp().equals(txtICPP.getText()))
                {
                    //if yes
                    JOptionPane.showMessageDialog(null,"This IC/Passport already exsists!","Error",JOptionPane.ERROR_MESSAGE);// pop up message showing that this ic or passport have been use
                    wrong++;// add 1 to this variable
                    break;// break this loop
                }
                //get information from booking class
                String roomid = room.getroomid();
                String dayafter = room.getdateafter();
                String day = room.getdate();
                //declare variable
                int x2cx1 =day.compareTo(sdf.format(jDateChooser1.getDate()));
                int y2cx1 =dayafter.compareTo(sdf.format(jDateChooser1.getDate()));
                int y2cy1 =dayafter.compareTo(txtCheckout.getText());
                int x2cy1 = day.compareTo(txtCheckout.getText());
                //to check if this room is available or not
                if ( roomid.equals(String.valueOf(cbID.getSelectedItem())) && (( y2cx1>=0 && x2cx1<=0 ) || ( x2cx1>=0 && x2cy1<=0 )|| ( x2cx1>=0 && y2cy1>=0 ))){
                    // if this room is not available
                    JOptionPane.showMessageDialog(null,"This room has been occupied and its not available","Error",JOptionPane.ERROR_MESSAGE);// error message
                    wrong++;// add 1 to this variable
                    break;
                }

            }
            inputFile.close();
        }
        catch(FileNotFoundException ex)// catch error
        {
            JOptionPane.showMessageDialog(null,"Error: "+ex,"Error",JOptionPane.ERROR_MESSAGE);// pop up message showing error
        }
        if (wrong ==0)
        {
            //get text from the form
            String n = txtName.getText();
            String i = txtICPP.getText();
            String p = txtPhone.getText();
            String e = txtEmail.getText();
            String r = String.valueOf(cbID.getSelectedItem());
            String d = String.valueOf(sdf.format(jDateChooser1.getDate()));
            String dts = String.valueOf(cbDos.getSelectedItem());
            String da = txtCheckout.getText();
            //to check if theform is filled up or not
            if (r.equals("Please Select") || dts.equals("Please Select") || n.equals("") || i.equals("") || p.equals("")|| e.equals("")|| d.equals("")|| da.equals("") )
            {
                //if not filled up
                JOptionPane.showMessageDialog(null,"Error: Please enter all the text fields before proceeding!","Error",JOptionPane.ERROR_MESSAGE);//error alert

            }else
            {
                try{
                    //writing information into the text file
                    FileWriter fw = new FileWriter("Booking.txt",true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    bw.write(n);
                    bw.newLine();
                    bw.write(i);
                    bw.newLine();
                    bw.write(p);
                    bw.newLine();
                    bw.write(e);
                    bw.newLine();
                    bw.write(r);
                    bw.newLine();
                    bw.write(d);
                    bw.newLine();
                    bw.write(dts);
                    bw.newLine();
                    bw.write(da);
                    bw.newLine();
                    bw.newLine();
                    bw.close();
                    JOptionPane.showMessageDialog(null,"Record has been saved successfully!","SYSTEM",JOptionPane.INFORMATION_MESSAGE);// pop up message saying record saved
                    //set the form to blank
                    txtName.setText("");
                    txtICPP.setText("");
                    txtPhone.setText("");
                    txtEmail.setText("");
                    jDateChooser1.setDate(cextra.getTime());
                    cbID.setSelectedIndex(0);
                    cbDos.setSelectedIndex(0);
                    txtCheckout.setText("");
                }
                catch (IOException ex)//catch error
                {
                    JOptionPane.showMessageDialog(null,"Could not save into file","Error",JOptionPane.ERROR_MESSAGE);//pop up message showing could not write into file
                }
            }
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckoutActionPerformed

    private void cbDosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDosItemStateChanged
        //to set the day after staying based on the day to stay
        String dayofstay= cbDos.getSelectedItem().toString();// getting day to stay value from combo box
        if (dayofstay.equals("Please Select"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 0);// add 0 day from the date given by date chooser
        }else if (dayofstay.equals("1 day"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 1);// add 1 day from the date given by date chooser
        }else if (dayofstay.equals("2 days"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 2);// add 2 days from the date given by date chooser
        }else if (dayofstay.equals("3 days"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 3);// add 3 days from the date given by date chooser
        }else if (dayofstay.equals("4 days"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 4);// add 4 days from the date given by date chooser
        }else if (dayofstay.equals("5 days"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 5);// add 5 days from the date given by date chooser
        }else if (dayofstay.equals("6 days"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 6);// add 6 days from the date given by date chooser
        }else if (dayofstay.equals("7 days"))
        {
            c.setTime(jDateChooser1.getDate());//set date given in date chooser
            c.add(Calendar.DAY_OF_MONTH, 7);// add 7 days from the date given by date chooser
        }
        txtCheckout.setText(sdf.format(c.getTime()));// set the date into text field after adding
    }//GEN-LAST:event_cbDosItemStateChanged

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        //to make this combo box and text field to blank everythig the date is change
        cbDos.setSelectedIndex(0);
        txtCheckout.setText("");
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        //set the form to blank
        txtName.setText("");
        txtICPP.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        cbID.setSelectedIndex(0);
        jDateChooser1.setDate(cextra.getTime());
        cbDos.setSelectedIndex(0);
        txtCheckout.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        // to make sure this text field only can enter digit
        char car = evt.getKeyChar();
        if(Character.isDigit(car) || car == KeyEvent.VK_BACK_SPACE)
        {
            txtPhone.setEditable(true);
        }
        else
        {
            txtPhone.setEditable(false);
        }
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void cbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Would you like to Logout?","Logout from System",JOptionPane.YES_NO_OPTION);//pop up box asking confirmation to exit the application
        if(n==JOptionPane.YES_OPTION)//if yes is clicked
        {
            login a = new login();
        a.setVisible(true);
        this.setVisible(false); //current frame will be invisible
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createbooking().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton btnReset;
    protected javax.swing.JButton btnSave;
    protected javax.swing.JComboBox<String> cbDos;
    protected javax.swing.JComboBox<String> cbID;
    private javax.swing.JMenu exitmenu;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menuitemcreatebooking;
    private javax.swing.JMenuItem menuitemdeletebooking;
    private javax.swing.JMenuItem menuitemeditbooking;
    private javax.swing.JMenuItem menuitemhomepage;
    private javax.swing.JMenuItem menuitemreceipt;
    private javax.swing.JMenuItem menuitemviewbooking;
    protected javax.swing.JTextField txtCheckout;
    protected javax.swing.JTextField txtEmail;
    protected javax.swing.JTextField txtICPP;
    protected javax.swing.JTextField txtName;
    protected javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
