/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelroombookingsystem;

import java.io.File;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Scanner;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class viewbooking extends javax.swing.JFrame {
    
    public viewbooking() {
        initComponents();
        jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
        TableColumn col = jTable1.getColumnModel().getColumn(0);
        col.setPreferredWidth(110);
        col=jTable1.getColumnModel().getColumn(1);
        col.setPreferredWidth(190);
        col=jTable1.getColumnModel().getColumn(2);
        col.setPreferredWidth(180);
        col=jTable1.getColumnModel().getColumn(3);
        col.setPreferredWidth(150);
        col=jTable1.getColumnModel().getColumn(4);
        col.setPreferredWidth(150);
        col=jTable1.getColumnModel().getColumn(5);
        col.setPreferredWidth(300);
        col=jTable1.getColumnModel().getColumn(6);
        col.setPreferredWidth(150);
        col=jTable1.getColumnModel().getColumn(7);
        col.setPreferredWidth(150);
        
    }
class Customer
{
    //set modifier and create variables
protected String name, icpp, email;
protected int phnum;
//contrustor
Customer(String n, String i, int p, String e)
{
    //set value
    name = n;
    icpp = i;
    email = e;
    phnum = p;
}
}


//subclass-inheritance
class Booking extends Customer
{
    // set modifire and create variables
    protected String daytostay, roomid, date, dateafter;
    //constructor
    Booking(String n, String i, int p, String e,String r, String d,String dts, String da)
    {
        super(n,i,p,e);// calling super class constructor
        //set value
        date = d;
        dateafter = da;
        daytostay = dts;
        roomid = r;
    }
    //encapsulation
    // to get name
    public String getname()
    {
        return name;
    }
    //to get ic/passport
    public String geticpp()
    {
        return icpp;
    }
    //to get phone number
    public int getphnum()
    {
        return phnum;
    }
    //to get email
    public String getemail()
    {
        return email;
    }
    //to get room id
    public String getroomid()
    {
        return roomid;
    }
    //to get date after staying
    public String getdateafter()
    {
        return dateafter;
    }
    //to get date start booking
    public String getdate()
    {
        return date;
    }
    //to get total day to stay
    public String getdaytostay()
    {
        return daytostay;
    }   
}
//to get date
Calendar c = new GregorianCalendar();
//set date format
SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnviewall = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuitemhomepage = new javax.swing.JMenuItem();
        menuitemcreatebooking = new javax.swing.JMenuItem();
        menuitemviewbooking = new javax.swing.JMenuItem();
        menuitemeditbooking = new javax.swing.JMenuItem();
        menuitemdeletebooking = new javax.swing.JMenuItem();
        menuitemreceipt = new javax.swing.JMenuItem();
        exitmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jTable1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RoomID", "Status", "Customer Name", "IC Passport", "Phone Number", "Email", "Check In Date", "Check Out Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable1.setShowGrid(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        // to show all room availability
        File file = new File("Booking.txt");
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        // add all room into jtable
        for(int z= 1; z <21; z++){
            Object [] a ={"Room"+z,"Available","","","","","",""};
            model.addRow(a);
            try
            {
                Scanner inputFile = new Scanner(file);
                test: while (inputFile.hasNext())
                {
                    //getting in
                    String n = inputFile.nextLine();
                    String i = inputFile.nextLine();
                    int p = inputFile.nextInt();
                    inputFile.nextLine();
                    String e = inputFile.nextLine();
                    String r = inputFile.nextLine();
                    String d = inputFile.nextLine();
                    String dts = inputFile.nextLine();
                    String da = inputFile.nextLine();
                    inputFile.nextLine();
                    // insert value to class
                    Booking room = new Booking(n,i,p,e,r,d,dts,da);
                    jDateChooser1.setDate(c.getTime());// set date
                    String day = room.getdate();// get value from class
                    String dayafter = room.getdateafter();// get value from class
                    //to check if this room is available or not
                    if (room.getroomid().equals("Room"+z)&& day.compareTo(sdf.format(jDateChooser1.getDate())) <= 0 && dayafter.compareTo(sdf.format(jDateChooser1.getDate())) > 0){
                        //if not available
                        model.removeRow(z-1);// remove the row above based on room number
                        Object [] b ={room.getroomid(),"Not Available",room.getname(),room.geticpp(),room.getphnum(),room.getemail(),room.getdate(),room.getdateafter()};
                        model.addRow(b);// add this room which show not available

                    }
                }

                inputFile.close();
            }

            catch(FileNotFoundException ex)//catch error

            {// if text file could not open
                System.out.println("Unable to open file due to "+ex);// pop up message

            }
        }

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Room Availability:");

        btnviewall.setBackground(new java.awt.Color(204, 204, 204));
        btnviewall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelroombookingsystem/icons8_magnifying_glass_tilted_left_30px_1.png"))); // NOI18N
        btnviewall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewallActionPerformed(evt);
            }
        });

        jDateChooser1.setToolTipText("");
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setDate(c.getTime());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel10.setText("View and Search Booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1401, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(493, 493, 493)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnviewall, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(515, 515, 515))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewall, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
        );

        menu.setText("MENU");

        menuitemhomepage.setText("Homepage");
        menuitemhomepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemhomepageActionPerformed(evt);
            }
        });
        menu.add(menuitemhomepage);

        menuitemcreatebooking.setText("Create Booking");
        menuitemcreatebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemcreatebookingActionPerformed(evt);
            }
        });
        menu.add(menuitemcreatebooking);

        menuitemviewbooking.setText("View Booking");
        menuitemviewbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemviewbookingActionPerformed(evt);
            }
        });
        menu.add(menuitemviewbooking);

        menuitemeditbooking.setText("Edit Booking");
        menuitemeditbooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemeditbookingActionPerformed(evt);
            }
        });
        menu.add(menuitemeditbooking);

        menuitemdeletebooking.setText("Delete Booking");
        menuitemdeletebooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemdeletebookingActionPerformed(evt);
            }
        });
        menu.add(menuitemdeletebooking);

        menuitemreceipt.setText("Receipt");
        menuitemreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemreceiptActionPerformed(evt);
            }
        });
        menu.add(menuitemreceipt);

        menubar.add(menu);

        exitmenu.setText("EXIT");
        exitmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitmenuMouseClicked(evt);
            }
        });

        menubar.add(Box.createHorizontalGlue());

        menubar.add(exitmenu);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewallActionPerformed
      // to check availability based on date
        File file = new File("Booking.txt");
DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
for (int check =model.getRowCount() -1; check >=0; check--)
                { model.removeRow(check);}    
        for(int z= 1; z <21; z++){
        Object [] a ={"Room"+z,"Available","","","","","",""};
        model.addRow(a);
try
      {
          Scanner inputFile = new Scanner(file);
        test: while (inputFile.hasNext())
        {
              String n = inputFile.nextLine();
              String i = inputFile.nextLine();
              int p = inputFile.nextInt();
              inputFile.nextLine();
              String e = inputFile.nextLine();
              String r = inputFile.nextLine();
              String d = inputFile.nextLine();
              String dts = inputFile.nextLine();
              String da = inputFile.nextLine();
              inputFile.nextLine();
              
              Booking room = new Booking(n,i,p,e,r,d,dts,da);
            String day = room.getdate();
            String dayafter = room.getdateafter();
        if (room.getroomid().equals("Room"+z)&& day.compareTo(sdf.format(jDateChooser1.getDate())) <= 0 && dayafter.compareTo(sdf.format(jDateChooser1.getDate())) >= 0){
               model.removeRow(z-1);
        Object [] b ={room.getroomid(),"Not Available",room.getname(),room.geticpp(),room.getphnum(),room.getemail(),room.getdate(),room.getdateafter()};
                model.addRow(b);
        }
        }
              
        
          inputFile.close();
        }
      
      catch(FileNotFoundException  ex)
      {
           System.out.println("Unable to open file due to "+ex);
                    
    }
}
    }//GEN-LAST:event_btnviewallActionPerformed

    private void menuitemhomepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemhomepageActionPerformed
        //to go to home page
        homepage homepage = new homepage();//set homepage as homepage
        homepage.setVisible(true);//open homepage page
        this.setVisible(false);//close current page

    }//GEN-LAST:event_menuitemhomepageActionPerformed

    private void menuitemcreatebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemcreatebookingActionPerformed
        //to go to create booking page
        createbooking c = new createbooking();// set create booking as c
        c.setVisible(true);// open create booking page
        this.setVisible(false);// close current page
    }//GEN-LAST:event_menuitemcreatebookingActionPerformed

    private void menuitemviewbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemviewbookingActionPerformed
        //to go to view booking page
        viewbooking page = new viewbooking();// set view booking as page
        page.setVisible(true);//open view booking page
        this.setVisible(false);//close current page
    }//GEN-LAST:event_menuitemviewbookingActionPerformed

    private void menuitemeditbookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemeditbookingActionPerformed
        //to go to edit booking page
        editbooking c = new editbooking();// set editbooking as c
        c.setVisible(true);// open edit booking page
        this.setVisible(false);// close this page
    }//GEN-LAST:event_menuitemeditbookingActionPerformed

    private void menuitemdeletebookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemdeletebookingActionPerformed
        //to go to delete booking page
        deletebooking c = new deletebooking();//set delete booking as c
        c.setVisible(true);//open delete booking page
        this.setVisible(false);//close this page
    }//GEN-LAST:event_menuitemdeletebookingActionPerformed

    private void menuitemreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemreceiptActionPerformed
        //to go to receipt page
        receipt c = new receipt();// set receipt as c
        c.setVisible(true);//open receipt page
        this.setVisible(false);//close this page
    }//GEN-LAST:event_menuitemreceiptActionPerformed

    private void exitmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitmenuMouseClicked
        int n = JOptionPane.showConfirmDialog(null,"Would you like to terminate?","Terminate System",JOptionPane.YES_NO_OPTION);//pop up box asking confirmation to exit the application
        if(n==JOptionPane.YES_OPTION)//if yes is clicked
        System.exit(0);//application exit

    }//GEN-LAST:event_exitmenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnviewall;
    private javax.swing.JMenu exitmenu;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem menuitemcreatebooking;
    private javax.swing.JMenuItem menuitemdeletebooking;
    private javax.swing.JMenuItem menuitemeditbooking;
    private javax.swing.JMenuItem menuitemhomepage;
    private javax.swing.JMenuItem menuitemreceipt;
    private javax.swing.JMenuItem menuitemviewbooking;
    // End of variables declaration//GEN-END:variables
}
